name: Generate Summary

on:
  push:
    paths:
      - "incidents.json"

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install openai pdf-lib

      - name: Generate summary from incidents.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node generatePdf.js
